export const strings = {
  //pages name
  SPLASH: 'Splash',
  LOGIN: 'Login',
  OTP: 'OtpScreen',
  SIGNUP: 'SignupScreen',
  REGISTRATION: 'Registration',
  UPDATE_PRO:'UpdateProfile',
  BIKE_MODAL: 'BikemodalScreen',
  INNER_BIKE_MODAL: 'InnerBikemodalScreen',
  HOME: 'Homescreen',
  MAP: 'MapScreen',
  BOTTOM_TAB: 'BottomTab',
  MARKET: 'MarketScreen',
  BIKERIDE: 'BikerideScreen',
  PROFILE_SCREEN: 'ProfileScreen',
  CREATE_POST: 'CreatePost',
  CREATE_GROUP: 'CreateGroup',
  CLUB_DETAILS: 'ClubDetails',
  GROUP_DETAILS:'GroupDetails',
  INVITE_FRIENDS: 'InviteFriendsScreen',
  CREATE_EVENT: 'CreateEvent',
  PRIVACY_POLICY_SCREENS:'PrivacyPolicyScreens',
  ABOUT_US:'AboutusScreen',
  BIKE_RIDE:'BikerideScreen',
  PRIVACY:'PrivacyPolicy',
  TERMS_CONDITION:'TermsConditions',
  HELP_SCREEN:'HelpScreen',
  RETURN_POLICY:'ReturnPolicy',
  BLOCK_SCREEN:'BlockScreen',
  SETTING:'SettingScreen',
  UPDATE_MOBILE:'UpdateMobile',
  USER_MAP:'UserMapScreen',
  CLUB_ONBOARDING:'Clubonboarding',
  SOS_SCREEN:'SOSScreen',
  FEED_BACK:'FeedbackScreen',
  EVENT_DETAILS: 'EventDetails',
  EVENT_PAGE: 'EventPage',
  UPDATE_EVENT:'UpdateEvent',
  CHAT_SCREEN:'ChatScreen',
  // login screen
  WELCOME: 'Welcome to The Biker Company',
  VERIFICATION_CODE:
    "We'll send you a verification code so we know you're a real user",
  MOBILE_NUMBER: 'Mobile Number',
  REGISTER: 'By registering your account you agree to our ',
  TERMS: 'Terms & Conditions',

  //profile screen
  COMPLETE_PROFILE: 'Complete Profile',
  UPDATE_PROFILE: 'Update Profile',
  //Bikemodal screen
  SELECT_COMPANY: 'Select your bike',

  //Inner
  DETAIL_PAGE:'DetailPage',
  CART_PAGE:'CartPage',
  CHECKOUT_PAGE:'CheckoutPage',
  FAVOURITES_PAGE:'FavoritesPage',
  NOTIFICATION_PAGE:'NotificationPage',
  ORDERS_SCREEN:'OrderScreen',
  ORDER_COMPLETED_SCREEN:'OrderCompletedScreen',
  TRACK_ORDER_SCREEN:'TrackingScreen',
  REQUESTCANCELORDER_SCREEN:'CancelOrderScreen',
  REVIEW_PRODUCT_SCREEN:'ReviewProductScreen',
  AddLocation: 'AddLocation',
  TagRiders: 'TagRiders',


  TopRoute_DETAIL:'TopRouteDetails',
  UPDATE_POST: 'UpdatePost',
  BLOCKED_FRIENDS:'BlockedFriends',  
  BLOCKED_USERS:'Blocked People',
};